### ISSUE TITLE
Introduce CI for code formatting checks

### ISSUE THREAD

**Issue by hkiyomaru** [ku-nlp/ja-vicuna-qa-benchmark#12]
## Why

At present, we lack a process for ensuring consistent code formatting across our repository.

## How

I recommend using [Github actions](https://github.com/features/actions).

## Implementation

If we introduce linters with pre-commit following #3, put the following configuration in `.github/workflows/lint.yml`.

```yaml
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run linters
        run: |
          pipx install pre-commit
          pre-commit run --all-files
```
