### ISSUE TITLE
Format the code

### ISSUE THREAD

**Issue by hkiyomaru** [ku-nlp/ja-vicuna-qa-benchmark#3]
## Why

Currently, the code is not formatted consistently, making the code hard to read.

## How

Introduce a code formatter which enforces a consistent coding style across the entire codebase.

## Implementation

I recommend using [Ruff](https://github.com/astral-sh/ruff) with [Pre-commit](https://pre-commit.com/). Ruff is a fast and reliable code formatter. By integrating it with 'pre-commit', we can automatically format code before each commit. The configuration file will be like:

```yaml
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
```
